version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - 7070:80
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
  php:
    build: ./php-fpm
    volumes:
      - ./www:/usr/share/nginx/html
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - 33099:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'